/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library.management.system;

import java.awt.print.Book;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet ;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author srija
 */
public class ReturnBook extends javax.swing.JFrame {
    Connection con=Connect.ConnectToDB();
    PreparedStatement pst=null;
    ResultSet res=null;
    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtstuid = new javax.swing.JTextField();
        txtbookid = new javax.swing.JTextField();
        txtbookname = new javax.swing.JTextField();
        txtstuname = new javax.swing.JTextField();
        txtissue = new javax.swing.JTextField();
        txtdue = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        butreturn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/allpageicon.jpg"))); // NOI18N
        jLabel1.setText("Return Book");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 98, 333, 62));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel2.setText("Student ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 213, 96, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel3.setText("Book ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 275, 115, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel4.setText("Book Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 337, 115, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel5.setText("Student Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 399, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel6.setText("Issue Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 460, 115, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel7.setText("Due Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 522, 115, -1));
        getContentPane().add(txtstuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 212, 137, -1));
        getContentPane().add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 274, 137, -1));
        getContentPane().add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 336, 137, -1));
        getContentPane().add(txtstuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 398, 137, -1));
        getContentPane().add(txtissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 459, 137, -1));
        getContentPane().add(txtdue, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 521, 137, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 40, 42));

        butreturn.setBackground(new java.awt.Color(153, 0, 51));
        butreturn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        butreturn.setForeground(new java.awt.Color(255, 255, 255));
        butreturn.setText(" RETURN ");
        butreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butreturnActionPerformed(evt);
            }
        });
        getContentPane().add(butreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 621, -1, 38));

        jButton2.setBackground(new java.awt.Color(153, 0, 51));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bokokok.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(txtstuid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please enter the student Id and search it");
            txtstuid.requestFocus();
            
        }
        else
        {
            try {
                //pst=con.prepareStatement("SELECT student.id AS student_ID, student.name AS student_name, book.id AS book_id,book.name AS book_name,book.issuedate,book.duedate FROM book INNER JOIN student ON student.id=book.studentid WHERE bookid=?");
                pst = con.prepareStatement("SELECT student.id AS student_ID, student.name AS student_name, book.id AS book_id, book.name AS book_name, book.issueDate, book.dueDate FROM book INNER JOIN student ON student.id = book.studentid WHERE student.id = ?");
                // assuming you're using student ID to search

                pst.setString(1,txtstuid.getText());
                res=pst.executeQuery();
                if(res.next())
                {
                    txtbookid.setText(res.getString(3));
                    txtstuid.setText(res.getString(1));
                    txtdue.setText(res.getString(6));
                    txtbookname.setText(res.getString(4));
                    txtissue.setText(res.getString(5));
                    txtstuname.setText(res.getString(2));
                    
                   
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Please enter valid student id");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } 
         

        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void butreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butreturnActionPerformed
        // TODO add your handling code here:
        /*if(txtstuid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please enter the student Id and search it");
            txtstuid.requestFocus();
            
        }
        else
        {
            try {
                pst=con.prepareStatement("UPDATE book SET STATUS=?,ISSUEDATE=?,DUEDATE=?,STUDENTID=? WHERE Book.id=?");
                pst.setString(1,"Issued");
                pst.setString(2,"");
                pst.setString(3,"");
                pst.setString(4,"");
                pst.setString(5,txtbookid.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Book Returned");
                txtissue.setText("");
                txtbookid.setText("");

                txtbookname.setText("");

                txtstuid.setText("");
                txtstuname.setText("");
                txtdue.setText("");



                
                
               
            } catch (SQLException ex) {
                Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }*/
        if(txtstuid.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Please enter the student ID and search it");
        txtstuid.requestFocus();
    } else {
        try {
            // Only update the status and reset the student ID without changing issueDate or dueDate
            pst = con.prepareStatement("UPDATE book SET STATUS=?, STUDENTID=NULL WHERE id=?");
            pst.setString(1, "Returned");  // Set the book status as 'Returned'
            pst.setString(2, txtbookid.getText());  // Use the Book ID to find the correct book record
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Book Returned");
            
            // Clear the fields after successful return
            txtissue.setText("");
            txtbookid.setText("");
            txtbookname.setText("");
            txtstuid.setText("");
            txtstuname.setText("");
            txtdue.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

        
        
    }//GEN-LAST:event_butreturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butreturn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtdue;
    private javax.swing.JTextField txtissue;
    private javax.swing.JTextField txtstuid;
    private javax.swing.JTextField txtstuname;
    // End of variables declaration//GEN-END:variables
}
